name: Flutter SonarQube Analysis

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Generate analysis + test coverage
        run: |
          flutter analyze > analysis.txt || true
          flutter test --coverage

      - name: Download sonar-scanner
        uses: warchant/setup-sonar-scanner@v7
        with:
          version: 5.0.1.3006

      - name: Run SonarQube Scan
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=flutter-boilerplate \
            -Dsonar.sources=lib \
            -Dsonar.tests=test \
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
            -Dsonar.pullrequest.branch=${{ github.head_ref }} \
            -Dsonar.pullrequest.base=${{ github.base_ref }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.dart.analysis.reportPath=analysis.txt \
            -Dsonar.dart.coverage.reportPaths=coverage/lcov.info \
            -Dsonar.dart.analysis.useDartAnalyzer=true \
            -Dsonar.flutter.analyze=true \
            -Dsonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.pb.dart
